controller:
  image: 
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: "2.476"
  resources:
    requests:
      cpu: "3000m"
      memory: "2048Mi"
    limits:
      cpu: "12000m"
      memory: "8192Mi"
  #    
  jenkinsUrlProtocol: "https"
  #
  podSecurityContextOverride:
    runAsNonRoot: false
    runAsUser: 1000
    supplementalGroups: [1000]
  #
  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    ingressClassName: alb
    hostName: ${hostName}
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: ${acm_arn}
      alb.ingress.kubernetes.io/group.name: ${group_name}
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      alb.ingress.kubernetes.io/healthcheck-path: /login
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: '140' # Do not change without checking compatibility with annotations
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '120'  # Do not change without checking compatibility with annotations
      alb.ingress.kubernetes.io/healthy-threshold-count: '2'       # Do not change without checking compatibility with annotations
      alb.ingress.kubernetes.io/unhealthy-threshold-count: '10'    # Do not change without checking compatibility with annotations
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 80
  #
  jenkinsUrl: ${hostName}
  servicePort: 80
  serviceType: NodePort
  probes:
    startupProbe:
      httpGet:
        path: '{{ default "" .Values.controller.jenkinsUriPrefix }}/login'
        port: http
      periodSeconds: 20
      timeoutSeconds: 10
      failureThreshold: 20
      #initialDelaySeconds: 600
      initialDelaySeconds: 30
    livenessProbe:
      failureThreshold: 15
      httpGet:
        path: '{{ default "" .Values.controller.jenkinsUriPrefix }}/login'
        port: http
      periodSeconds: 30
      timeoutSeconds: 15
      #initialDelaySeconds: 120
      initialDelaySeconds: 30
    readinessProbe:
      failureThreshold: 15
      httpGet:
        path: '{{ default "" .Values.controller.jenkinsUriPrefix }}/login'
        port: http
      periodSeconds: 30
      timeoutSeconds: 15
      initialDelaySeconds: 30
  #
  JCasC:
    defaultConfig: false
  #
  installPlugins:
    - amazon-ecr:1.136.v914ea_5948634
    - ansible:403.v8d0ca_dcb_b_502
    - ansicolor:1.0.4
    - antisamy-markup-formatter:162.v0e6ec0fcfcf6
    - apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
    - apache-httpcomponents-client-5-api:5.3.1-117.v4d95117cd34f
    - asm-api:9.7-33.v4d23ef79fcc8
    - authentication-tokens:1.119.v50285141b_7e1
    - aws-credentials:231.v08a_59f17d742
    - aws-java-sdk-ec2:1.12.767-467.vb_e93f0c614b_6
    - aws-java-sdk-ecr:1.12.767-467.vb_e93f0c614b_6
    - aws-java-sdk-minimal:1.12.767-467.vb_e93f0c614b_6
    - azure-cli:0.9
    - azure-credentials:312.v0f3973cd1e59
    - azure-sdk:174.va_89c1df897d2
    - blueocean-commons:1.27.14
    - blueocean-pipeline-scm-api:1.27.14
    - blueocean-rest:1.27.14
    - bootstrap5-api:5.3.3-1
    - bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
    - branch-api:2.1178.v969d9eb_c728e
    - caffeine-api:3.1.8-133.v17b_1ff2e0599
    - checks-api:2.2.1
    - cloudbees-folder:6.951.v5f91d88d76b_b_
    - command-launcher:115.vd8b_301cc15d0
    - commons-lang3-api:3.17.0-84.vb_b_938040b_078
    - commons-text-api:1.12.0-129.v99a_50df237f7
    - config-file-provider:978.v8e85886ffdc4
    - configuration-as-code:1850.va_a_8c31d3158b_
    - configuration-as-code-groovy:1.1
    - credentials:1371.vfee6b_095f0a_3
    - credentials-binding:681.vf91669a_32e45
    - custom-folder-icon:2.14
    - data-tables-api:2.1.6-1
    - disable-github-multibranch-status:1.2
    - display-url-api:2.204.vf6fddd8a_8b_e9
    - docker-commons:443.v921729d5611d
    - durable-task:568.v8fb_5c57e8417
    - echarts-api:5.5.1-1
    - eddsa-api:0.3.0-4.v84c6f0f4969e
    - embeddable-build-status:487.va_0ef04c898a_2
    - external-monitor-job:215.v2e88e894db_f8
    - font-awesome-api:6.6.0-2
    - gatling:1.3.0
    - generic-webhook-trigger:2.2.2
    - git:5.4.1
    - git-client:5.0.0
    - github:1.40.0
    - github-api:1.321-478.vc9ce627ce001
    - github-branch-source:1797.v86fdb_4d57d43
    - github-checks:583.v9c7da_3c0a_6d5
    - git-parameter:0.9.19
    - git-server:126.v0d945d8d2b_39
    - gson-api:2.11.0-41.v019fcf6125dc
    - hashicorp-vault-pipeline:1.4
    - hashicorp-vault-plugin:370.v946b_53544a_30
    - htmlpublisher:1.36
    - instance-identity:185.v303dc7c645f9
    - ionicons-api:74.v93d5eb_813d5f
    - jackson2-api:2.17.0-379.v02de8ec9f64c
    - jakarta-activation-api:2.1.3-1
    - jakarta-mail-api:2.1.3-1
    - javax-activation-api:1.2.0-7
    - javax-mail-api:1.6.2-10
    - jaxb:2.3.9-1
    - jdk-tool:80.v8a_dee33ed6f0
    - jjwt-api:0.11.5-112.ve82dfb_224b_a_d
    - joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
    - jquery3-api:3.7.1-2
    - jsch:0.2.16-86.v42e010d9484b_
    - json-api:20240303-41.v94e11e6de726
    - json-path-api:2.9.0-58.v62e3e85b_a_655
    - junit:1300.v03d9d8a_cf1fb_
    - kubernetes:4285.v50ed5f624918
    - kubernetes-cli:1.12.1
    - kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
    - kubernetes-credentials:189.v90a_488b_d1d65
    - kubernetes-credentials-provider:1.262.v2670ef7ea_0c5
    - lockable-resources:1301.v0e3b_da_4b_4462
    - mailer:472.vf7c289a_4b_420
    - matrix-auth:3.2.2
    - matrix-project:832.va_66e270d2946
    - metrics:4.2.21-451.vd51df8df52ec
    - mina-sshd-api-common:2.13.2-125.v200281b_61d59
    - mina-sshd-api-core:2.13.2-125.v200281b_61d59
    - multibranch-build-strategy-extension:51.v88f14e2a_4075
    - okhttp-api:4.11.0-181.v1de5b_83857df
    - oss-symbols-api:63.ve7560ec12b_e6
    - parameterized-scheduler:277.v61a_4b_a_49a_c5c
    - permissive-script-security:0.7
    - pipeline-build-step:540.vb_e8849e1a_b_d8
    - pipeline-graph-analysis:216.vfd8b_ece330ca_
    - pipeline-groovy-lib:730.ve57b_34648c63
    - pipeline-input-step:495.ve9c153f6067b_
    - pipeline-milestone-step:119.vdfdc43fc3b_9a_
    - pipeline-model-api:2.2214.vb_b_34b_2ea_9b_83
    - pipeline-model-definition:2.2214.vb_b_34b_2ea_9b_83
    - pipeline-model-extensions:2.2214.vb_b_34b_2ea_9b_83
    - pipeline-rest-api:2.34
    - pipeline-stage-step:312.v8cd10304c27a_
    - pipeline-stage-tags-metadata:2.2214.vb_b_34b_2ea_9b_83
    - pipeline-stage-view:2.34
    - plain-credentials:183.va_de8f1dd5a_2b_
    - plugin-util-api:4.1.0
    - postbuild-task:1.9
    - prism-api:1.29.0-17
    - pubsub-light:1.18
    - role-strategy:743.v142ea_b_d5f1d3
    - saml:4.487.v9f1c3328f1c0
    - scm-api:696.v778d637b_a_762
    - script-security:1361.v913100720139
    - slack:741.v00f9591c586d
    - snakeyaml-api:2.3-123.v13484c65210a_
    - sonar:2.17.2
    - ssh-agent:376.v8933585c69d3
    - ssh-credentials:343.v884f71d78167
    - sshd:3.330.vc866a_8389b_58
    - structs:338.v848422169819
    - terraform:1.0.10
    - timestamper:1.27
    - token-macro:400.v35420b_922dcb_
    - trilead-api:2.147.vb_73cc728a_32e
    - variant:60.v7290fc0eb_b_cd
    - workflow-aggregator:600.vb_57cdd26fdd7
    - workflow-api:1336.vee415d95c521
    - workflow-basic-steps:1058.vcb_fc1e3a_21a_9
    - workflow-cps:3961.ve48ee2c44a_b_3
    - workflow-durable-task-step:1371.vb_7cec8f3b_95e
    - workflow-job:1436.vfa_244484591f
    - workflow-multibranch:795.ve0cb_1f45ca_9a_
    - workflow-scm-step:427.v4ca_6512e7df1
    - workflow-step-api:678.v3ee58b_469476
    - workflow-support:920.v59f71ce16f04
    - prometheus:784.vea_eca_f6592eb_
  #
  prometheus:
    enabled: true
    serviceMonitorNamespace:
    scrapeInterval: 60s
    scrapeEndpoint: /prometheus
#
persistence:
  existingClaim: ${pvc}
#
rbac:
  create: true
#